"""
Test_pkg application package for Jarvis-CD.
This is an application that runs and completes automatically.
"""
from jarvis_cd.core.pkg import Application


class Test_pkg(Application):
    """
    Test_pkg application implementation.
    """
    
    def _init(self):
        """
        Initialize application-specific variables.
        Don't assume that self.config is initialized.
        """
        self.input_file = None
        self.output_file = None
        self.nprocs = None
        
    def _configure_menu(self):
        """
        Create a CLI menu for the configurator method.
        
        :return: List of argument dictionaries
        """
        return [
            {
                'name': 'input_file',
                'msg': 'Path to input file',
                'type': str,
                'default': '/tmp/test_pkg_input.dat'
            },
            {
                'name': 'output_file',
                'msg': 'Path to output file',
                'type': str,
                'default': '/tmp/test_pkg_output.dat'
            },
            {
                'name': 'nprocs',
                'msg': 'Number of processes',
                'type': int,
                'default': 1
            },
            {
                'name': 'ppn',
                'msg': 'Processes per node',
                'type': int,
                'default': 1
            }
        ]
        
    def configure(self, **kwargs):
        """
        Configure the application with given parameters.
        
        :param kwargs: Configuration parameters
        """
        self.update_config(kwargs, rebuild=False)
        
        # Validate configuration
        if self.config['nprocs'] <= 0:
            raise ValueError("Number of processes must be positive")
            
        print(f"Configured test_pkg application:")
        print(f"  Input: {self.config['input_file']}")
        print(f"  Output: {self.config['output_file']}")
        print(f"  Processes: {self.config['nprocs']}")
        
    def start(self):
        """
        Run the test_pkg application.
        """
        print(f"Running test_pkg application")
        
        # Prepare input data if needed
        self._prepare_input()
        
        # Example application execution - replace with actual commands
        # cmd = [
        #     'test_pkg',
        #     '--input', self.config['input_file'],
        #     '--output', self.config['output_file']
        # ]
        
        # Example MPI execution:
        # from jarvis_util import MpiExecInfo, Exec
        # Exec(' '.join(cmd),
        #      MpiExecInfo(env=self.mod_env,
        #                  hostfile=self.hostfile,
        #                  nprocs=self.config['nprocs'],
        #                  ppn=self.config['ppn']))
        
        print(f"test_pkg application completed")
        
    def stop(self):
        """
        Stop the application (usually not needed for apps).
        """
        print(f"Stopping test_pkg application")
        
    def clean(self):
        """
        Clean up application data and temporary files.
        """
        print(f"Cleaning test_pkg application data")
        
        # Remove output files
        import os
        if os.path.exists(self.config['output_file']):
            os.remove(self.config['output_file'])
            
        # Remove any temporary files
        # os.system(f'rm -f {self.config["output_file"]}*')
        
        print(f"test_pkg application cleaned")
        
    def _prepare_input(self):
        """
        Prepare input data for the application.
        """
        import os
        
        input_file = self.config['input_file']
        
        # Create input directory if needed
        os.makedirs(os.path.dirname(input_file), exist_ok=True)
        
        # Generate or copy input data
        if not os.path.exists(input_file):
            print(f"Generating input file: {input_file}")
            with open(input_file, 'w') as f:
                f.write(f"# test_pkg input data\n")
                f.write(f"# Generated by Jarvis-CD\n")
