"""
Container-based IOR deployment using Docker/Podman compose.
"""
from jarvis_cd.core.container_pkg import ContainerApplication
from pathlib import Path


class IorContainer(ContainerApplication):
    """
    Container-based IOR deployment.
    """

    def augment_container(self) -> str:
        """
        Generate Dockerfile commands to install IOR in a container.

        :return: Dockerfile commands as a string
        """
        return """
# Install IOR
RUN . "${SPACK_DIR}/share/spack/setup-env.sh" && \\
    spack install -y ior

# Copy required spack executables and libraries to /usr
RUN . "${SPACK_DIR}/share/spack/setup-env.sh" && \\
    spack load iowarp && \\
    cp -r $(spack location -i python)/bin/* /usr/bin || true && \\
    cp -r $(spack location -i py-pip)/bin/* /usr/bin || true && \\
    cp -r $(spack location -i python-venv)/bin/* /usr/bin || true && \\
    PYTHON_PATH=$(readlink -f /usr/bin/python3) && \\
    PYTHON_PREFIX=$(dirname $(dirname $PYTHON_PATH)) && \\
    cp -r $(spack location -i mpi)/bin/* /usr/bin || true && \\
    cp -r $(spack location -i ior)/bin/* /usr/bin || true && \\
    cp -r $(spack location -i iowarp-runtime)/bin/* /usr/bin || true && \\
    cp -r $(spack location -i iowarp-cte)/bin/* /usr/bin || true && \\
    cp -r $(spack location -i cte-hermes-shm)/bin/* /usr/bin || true && \\
    for pkg in $(spack find --format '{name}' | grep '^py-'); do \\
        cp -r $(spack location -i $pkg)/lib/* $PYTHON_PREFIX/lib/ 2>/dev/null || true; \\
        cp -r $(spack location -i $pkg)/bin/* /usr/bin 2>/dev/null || true; \\
    done && \\
    sed -i '1s|.*|#!/usr/bin/python3|' /usr/bin/jarvis && \\
    echo "Spack packages copied to /usr directory"
"""

    def _configure(self, **kwargs):
        """
        Configure container deployment.
        For pipeline-level containers, configuration files are generated by the pipeline.

        :param kwargs: Configuration parameters for this pkg.
        :return: None
        """
        # Call parent configuration
        super()._configure(**kwargs)

        # Note: For pipeline-level containers, Dockerfile and compose files are generated
        # by the pipeline's _generate_pipeline_dockerfile() and _generate_pipeline_compose_file()
        # methods, not by individual packages.

    def _generate_dockerfile(self):
        """
        Generate Dockerfile for IOR container.
        Uses the base image specified in the pipeline's container_base.

        Note: This method is deprecated for pipeline-level containers.
        Use pipeline.container_ssh_port instead.
        """
        # Use pipeline-level SSH port if available, otherwise fallback to default
        ssh_port = getattr(self.pipeline, 'container_ssh_port', 2222)

        # Get the base image to build FROM
        if hasattr(self.pipeline, 'container_base') and self.pipeline.container_base:
            base_image = self.pipeline.container_base
        else:
            # Fallback to default if pipeline doesn't have container_base
            base_image = 'iowarp/iowarp-build:latest'

        # sshd always listens on the configured port inside the container
        # - For host network: sshd listens directly on this port
        # - For port mapping: sshd listens on this port, gets mapped to host
        sshd_port = ssh_port

        dockerfile_content = f"""FROM {base_image}

# Disable prompt during packages installation.
ARG DEBIAN_FRONTEND=noninteractive

# Configure SSH daemon to listen on port {sshd_port}
RUN sed -i 's/^#*Port .*/Port {sshd_port}/' /etc/ssh/sshd_config
"""

        dockerfile_path = Path(self.shared_dir) / 'Dockerfile'
        with open(dockerfile_path, 'w') as f:
            f.write(dockerfile_content)

        print(f"Generated Dockerfile: {dockerfile_path}")
        print(f"Using base image: {base_image}")
