FROM ##BUILD_IMAGE## AS builder
FROM ##BASE_IMAGE##

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    gdb gdbserver \
    && rm -rf /var/lib/apt/lists/*

# Copy WarpX binary and example inputs from build container
COPY --from=builder /opt/warpx/build/bin/warpx.3d.MPI.CUDA.SP.PSP.OPMD.EB.QED /usr/bin/warpx
COPY --from=builder /opt/warpx/Examples /opt/warpx/Examples

ENV PATH=/usr/bin:${PATH}

CMD ["/bin/bash"]
